# Generated by Django 5.2.17 on 2026-08-07 14:20

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ecosystem', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Election ID')),
                ('election_type', models.CharField(choices=[('city', 'City Election (Supreme Minister)'), ('mohalla', 'Mohalla Election (Mohalla Minister)')], max_length=10, verbose_name='Election Type')),
                ('phase', models.CharField(choices=[('nomination', 'Nomination (Parcha)'), ('allocation', 'Symbol Allocation'), ('campaign', 'Campaign (Prachar)'), ('code_of_conduct', 'Achaar Sanhita (Code of Conduct)'), ('voting', 'Voting'), ('counting', 'Counting'), ('completed', 'Completed (Results Declared)')], default='nomination', max_length=20, verbose_name='Current Phase')),
                ('start_date', models.DateTimeField(verbose_name='Start Date')),
                ('end_date', models.DateTimeField(verbose_name='End Date')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elections', to='ecosystem.city', verbose_name='City')),
                ('mohalla', models.ForeignKey(blank=True, help_text='Mohalla election ke liye set karo. City election mein null hoga.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elections', to='ecosystem.mohalla', verbose_name='Mohalla')),
            ],
            options={
                'verbose_name': 'Election',
                'verbose_name_plural': 'Elections',
                'db_table': 'election_election',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Candidate ID')),
                ('manifesto', models.TextField(help_text='Candidate ka election manifesto / vaade', verbose_name='Manifesto')),
                ('symbol', models.CharField(blank=True, default='', help_text='Emoji symbol — e.g., 🚲, 🌺, 🏠 (Admin allocate karta hai)', max_length=10, verbose_name='Election Symbol')),
                ('vote_count', models.IntegerField(default=0, help_text='Total votes received (Redis queue se count hoti hai)', verbose_name='Vote Count')),
                ('is_approved', models.BooleanField(default=False, help_text='Admin ne approve kiya hai ya nahi (symbol allocation phase mein)', verbose_name='Approved by Admin')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Nominated At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidacies', to=settings.AUTH_USER_MODEL, verbose_name='Candidate User')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='election.election', verbose_name='Election')),
            ],
            options={
                'verbose_name': 'Candidate',
                'verbose_name_plural': 'Candidates',
                'db_table': 'election_candidate',
                'ordering': ['-vote_count'],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Vote ID')),
                ('device_id', models.CharField(help_text='Physical device identifier — ensures 1 device = 1 vote', max_length=255, verbose_name='Device ID')),
                ('hashed_token', models.CharField(help_text='Unique hash to prevent double voting (election_id + device_id + user_id hash)', max_length=255, unique=True, verbose_name='Hashed Vote Token')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Voted At')),
                ('candidate', models.ForeignKey(blank=True, help_text='Kis candidate ko vote diya (tracking ke liye)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_votes', to='election.candidate', verbose_name='Voted For')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='election.election', verbose_name='Election')),
            ],
            options={
                'verbose_name': 'Vote',
                'verbose_name_plural': 'Votes',
                'db_table': 'election_vote',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='election',
            index=models.Index(fields=['city', 'election_type'], name='idx_election_city_type'),
        ),
        migrations.AddIndex(
            model_name='election',
            index=models.Index(fields=['phase'], name='idx_election_phase'),
        ),
        migrations.AddIndex(
            model_name='election',
            index=models.Index(fields=['-start_date'], name='idx_election_start'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['election', 'is_approved'], name='idx_candidate_election_appr'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['-vote_count'], name='idx_candidate_votes'),
        ),
        migrations.AlterUniqueTogether(
            name='candidate',
            unique_together={('election', 'user')},
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['election', 'device_id'], name='idx_vote_election_device'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['hashed_token'], name='idx_vote_hashed_token'),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('election', 'device_id')},
        ),
    ]
