# Generated by Django 5.2.17 on 2026-08-07 14:20

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='City ID')),
                ('name', models.CharField(help_text='City ka naam — e.g., "Kandhla"', max_length=100, unique=True, verbose_name='City Name')),
                ('state', models.CharField(help_text='State jismein city hai — e.g., "Uttar Pradesh"', max_length=100, verbose_name='State')),
                ('samvidhan_content', models.TextField(blank=True, default='', help_text='City ki Samvidhan ka HTML/RichText content — Django Admin se manage hota hai', verbose_name='Samvidhan (Constitution)')),
                ('is_code_of_conduct_active', models.BooleanField(default=False, help_text='Jab True ho, posting disabled ho jati hai (Election ke dauran)', verbose_name='Achaar Sanhita Active')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'db_table': 'ecosystem_city',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Mohalla',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Mohalla ID')),
                ('name', models.CharField(help_text='Mohalla ka naam — e.g., "Mohalla Qazi Sarai"', max_length=150, verbose_name='Mohalla Name')),
                ('population_count', models.IntegerField(default=0, help_text='Registered users ki total count is mohalla mein', verbose_name='Population Count')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mohallas', to='ecosystem.city', verbose_name='City')),
            ],
            options={
                'verbose_name': 'Mohalla',
                'verbose_name_plural': 'Mohallas',
                'db_table': 'ecosystem_mohalla',
                'ordering': ['city', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Cabinet Entry ID')),
                ('department_name', models.CharField(help_text='Department ka naam — e.g., "Home Minister", "Infra Head"', max_length=100, verbose_name='Department')),
                ('ruby_color', models.CharField(help_text='VIP badge ka color — e.g., "violet", "grey"', max_length=30, verbose_name='Ruby Badge Color')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cabinet_positions', to=settings.AUTH_USER_MODEL, verbose_name='Cabinet Member')),
                ('city', models.ForeignKey(blank=True, help_text='City level cabinet ke liye (Supreme Minister ki team)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city_cabinet', to='ecosystem.city', verbose_name='City')),
                ('mohalla', models.ForeignKey(blank=True, help_text='Mohalla level cabinet ke liye (Mohalla Minister ki team)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mohalla_cabinet', to='ecosystem.mohalla', verbose_name='Mohalla')),
            ],
            options={
                'verbose_name': 'Cabinet Member',
                'verbose_name_plural': 'Cabinet Members',
                'db_table': 'ecosystem_cabinet',
                'ordering': ['city', 'mohalla', 'department_name'],
            },
        ),
        migrations.CreateModel(
            name='MohallaChangeRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Request ID')),
                ('reason', models.TextField(help_text='Mohalla change karne ki wajah', verbose_name='Reason')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10, verbose_name='Status')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('target_mohalla', models.ForeignKey(help_text='Jis mohalla mein jaana chahta hai', on_delete=django.db.models.deletion.CASCADE, related_name='incoming_requests', to='ecosystem.mohalla', verbose_name='Target Mohalla')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mohalla_change_requests', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Mohalla Change Request',
                'verbose_name_plural': 'Mohalla Change Requests',
                'db_table': 'ecosystem_mohallarequest',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='mohalla',
            index=models.Index(fields=['city'], name='idx_mohalla_city'),
        ),
        migrations.AlterUniqueTogether(
            name='mohalla',
            unique_together={('city', 'name')},
        ),
        migrations.AddIndex(
            model_name='cabinet',
            index=models.Index(fields=['city', 'is_active'], name='idx_cabinet_city_active'),
        ),
        migrations.AddIndex(
            model_name='cabinet',
            index=models.Index(fields=['mohalla', 'is_active'], name='idx_cabinet_mohalla_active'),
        ),
        migrations.AddIndex(
            model_name='mohallachangerequest',
            index=models.Index(fields=['user', 'status'], name='idx_mohallareq_user_status'),
        ),
    ]
