# Generated by Django 5.2.17 on 2026-08-10 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecosystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='is_emergency_rule_active',
            field=models.BooleanField(default=False, help_text='Jab True ho, system fully locked (No posts, no new users, no mohalla changes)', verbose_name='Emergency Rule Active'),
        ),
    ]
