// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCZ1u-x26a9vZFiUnJqPXCAPQHCpaH0OE',
    appId: '1:881010318377:web:cbf37210ab386baa889038',
    messagingSenderId: '881010318377',
    projectId: 'diz-chunaav-app',
    authDomain: 'diz-chunaav-app.firebaseapp.com',
    storageBucket: 'diz-chunaav-app.firebasestorage.app',
    measurementId: 'G-BCSWWS97KZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkRQUoBYs6YYpr85y1SqoZVZqr_cAMGTM',
    appId: '1:881010318377:android:8247c5cd89b4b6b4889038',
    messagingSenderId: '881010318377',
    projectId: 'diz-chunaav-app',
    storageBucket: 'diz-chunaav-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAk7JE2Uou-8cot-5d4HIhvxL84NDxhGQ',
    appId: '1:881010318377:ios:b46d3838e0c29864889038',
    messagingSenderId: '881010318377',
    projectId: 'diz-chunaav-app',
    storageBucket: 'diz-chunaav-app.firebasestorage.app',
    iosBundleId: 'com.example.kandhlaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAk7JE2Uou-8cot-5d4HIhvxL84NDxhGQ',
    appId: '1:881010318377:ios:b46d3838e0c29864889038',
    messagingSenderId: '881010318377',
    projectId: 'diz-chunaav-app',
    storageBucket: 'diz-chunaav-app.firebasestorage.app',
    iosBundleId: 'com.example.kandhlaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCZ1u-x26a9vZFiUnJqPXCAPQHCpaH0OE',
    appId: '1:881010318377:web:7046f40665553e45889038',
    messagingSenderId: '881010318377',
    projectId: 'diz-chunaav-app',
    authDomain: 'diz-chunaav-app.firebaseapp.com',
    storageBucket: 'diz-chunaav-app.firebasestorage.app',
    measurementId: 'G-H7VEFCP82C',
  );
}
