# Generated by Django 5.2.17 on 2026-08-07 14:20

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='User ID')),
                ('google_id', models.CharField(blank=True, help_text='Google OAuth unique identifier', max_length=255, null=True, unique=True, verbose_name='Google ID')),
                ('device_id', models.CharField(blank=True, db_index=True, default='', help_text='Physical device identifier for anti-fraud voting', max_length=255, verbose_name='Device ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('name', models.CharField(max_length=150, verbose_name='Full Name')),
                ('avatar_url', models.URLField(blank=True, default='', help_text='Google profile picture URL', max_length=500, verbose_name='Avatar URL')),
                ('role', models.CharField(choices=[('citizen', 'Citizen'), ('mohalla_minister', 'Mohalla Minister'), ('city_minister', 'City Minister'), ('supreme_minister', 'Supreme Minister')], default='citizen', help_text='User role for RBAC permissions', max_length=20, verbose_name='Role')),
                ('credibility_score', models.IntegerField(default=100, help_text='Reputation score — nomination ke liye minimum 500 chahiye', verbose_name='Credibility Score')),
                ('strike_count', models.IntegerField(default=0, help_text='Moderation strikes — 4th strike = permanent ban', verbose_name='Strike Count')),
                ('ban_until', models.DateTimeField(blank=True, help_text='Timestamp tak user banned hai. Null = not banned.', null=True, verbose_name='Banned Until')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_staff', models.BooleanField(default=False, help_text='Django admin access ke liye.', verbose_name='Staff Status')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'accounts_user',
                'ordering': ['-created_at'],
            },
        ),
    ]
