# Generated by Django 5.2.17 on 2026-08-10 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='apple_id',
            field=models.CharField(blank=True, help_text='Apple Sign-In unique identifier', max_length=255, null=True, unique=True, verbose_name='Apple ID'),
        ),
    ]
