# Generated by Django 5.2.17 on 2026-08-07 14:20

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ecosystem', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Concern',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Concern ID')),
                ('image_url', models.URLField(help_text='Concern ki supporting image (zaroori hai)', max_length=500, verbose_name='Image URL')),
                ('description', models.TextField(help_text='Issue ki detailed description', verbose_name='Description')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('city_priority', 'City Priority'), ('resolved', 'Resolved')], default='pending', max_length=15, verbose_name='Status')),
                ('support_count', models.IntegerField(default=0, help_text='Kitne logon ne Support kiya', verbose_name='Support Count')),
                ('do_not_support_count', models.IntegerField(default=0, help_text='Kitne logon ne Do Not Support kiya', verbose_name='Do Not Support Count')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('mohalla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concerns', to='ecosystem.mohalla', verbose_name='Mohalla')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concerns', to=settings.AUTH_USER_MODEL, verbose_name='Raised By')),
            ],
            options={
                'verbose_name': 'Concern (Samasya)',
                'verbose_name_plural': 'Concerns (Samasya)',
                'db_table': 'content_concern',
                'ordering': ['-support_count', '-created_at'],
                'indexes': [models.Index(fields=['mohalla', 'status'], name='idx_concern_mohalla_status'), models.Index(fields=['user'], name='idx_concern_user'), models.Index(fields=['-support_count'], name='idx_concern_support')],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Post ID')),
                ('content_text', models.TextField(blank=True, null=True, verbose_name='Content Text')),
                ('image_url', models.URLField(blank=True, help_text='Post ki image (Videos disabled to save storage)', max_length=500, null=True, verbose_name='Image URL')),
                ('post_type', models.CharField(choices=[('normal', 'Normal Post'), ('announcement', 'Announcement (Pinned)'), ('ad', 'Advertisement'), ('official_order', 'Official Order')], default='normal', max_length=20, verbose_name='Post Type')),
                ('is_anonymous', models.BooleanField(default=False, help_text='True = Whistleblower anonymous post (public ko anonymous dikhega, Admin/SM track kar sakta hai)', verbose_name='Anonymous Post')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('mohalla', models.ForeignKey(help_text='Jis mohalla mein ye post dikhegi', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='ecosystem.mohalla', verbose_name='Mohalla')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'db_table': 'content_post',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['mohalla', '-created_at'], name='idx_post_mohalla_date'), models.Index(fields=['user'], name='idx_post_user'), models.Index(fields=['post_type'], name='idx_post_type')],
            },
        ),
    ]
